### PR TITLE
Add borderRadius prop

### PR DESCRIPTION
**Pull request by kacgrzes**
- add `.prettierrc` config
- add Slider component
- add `borderRadius` prop
- clean up Avatar components code

Zrzut ekranu 2021-05-28 o 17 37 38
Zrzut ekranu 2021-05-28 o 17 37 47
Zrzut ekranu 2021-05-28 o 17 37 54

### CODE REVIEW

**Comment by alexmarles** [comment]
@kacgrzes It could have been a better approach to create separate PR for the Prettier configuration and the Border Radius feature. This would allow the maintainers to review the code styling you are proposing here, because the changes are quite substantial.

**Comment by kacgrzes** [comment]
> @kacgrzes It could have been a better approach to create separate PR for the Prettier configuration and the Border Radius feature. This would allow the maintainers to review the code styling you are proposing here, because the changes are quite substantial.

sure thing 🦾

**Comment by josepmartins** [comment]
Hey @kacgrzes, agree with @alexmarles here, we should split this PR to cover the different proposals, at least for the `. prettierrc` config.

When it comes to the Border Radius approach, we will soon release another strategy for serving images without borders, as some variants were only conceived to have a circular shape. For that reason, using CSS `border-radius` property on the `Ring` variant won't work:

Screenshot 2021-05-30 at 08 20 16


Thanks for you time ✨🙏.

**Comment by kacgrzes** [comment]
> Hey @kacgrzes, agree with @alexmarles here, we should split this PR to cover the different proposals, at least for the `. prettierrc` config.
> 
> When it comes to the Border Radius approach, we will soon release another strategy for serving square images properly, as some variants were only conceived to have circular shapes. For that reason, using CSS `border-radius` property on the `Ring` variant won't work:
> 
> Screenshot 2021-05-30 at 08 20 16
> 
> Thanks for you time ✨🙏.

It would work! I've covered all the cases. Take a look :) I know it's not perfect, but I like it

Zrzut ekranu 2021-05-31 o 18 24 50
Zrzut ekranu 2021-05-31 o 18 24 43

**Comment by kacgrzes** [comment]
@josepmartins also, I'll create a PR with my `.prettierrc` config so we could eventually apply these changes after prettier configuration

**Comment by G9000** [comment]
I was wondering, what happened to the border-radius or rounded square implementation status?

**Pull request closed without merging**
