### PR TITLE
feat(avatar): use react useId for masks

### PR DESCRIPTION
**Pull request by Multiply**

### CODE REVIEW

**Comment by Multiply** [comment]
This has been suggested in previous issues and I've just done it again for one of my own projects.

If you'd like the contribution in a different shape, feel free to let me know.

**Comment by neilpoulin** [comment]
This would fix a problem I have run into where I have multiple instances of identically configured Avatars on the page, but some may get hidden via javascript (due to popovers, modals, etc) which ends up causing the avatars to disappear in all cases. 

I forked this repo and implemented a fix similar to what the author of this PR did, except I used `const [maskId] = useState(uuid());` instead of `React.useId()` because I am not able to use React 18.

**Comment by Multiply** [comment]
Shouldn't be stale, as there have been node code changes to the master branch since I rebased last.

**Comment by josepmartins** [comment]
Hey there! This should be fixed with the latest `1.10.0` version. We ended up using the useID hook and upgrading the library to use React 18 version. 

Thanks for your patience and time 👋

**Pull request closed without merging**
